title: Xinyu Hua
description: Ph.D. student at Northeastern University
google_analytics: UA-143075473-1
theme: jekyll-theme-leap-day
gems:
  - jekyll-font-awesome-sass

url: http://xinyuhua.github.io/
resourceurl: '/resources'

author:
    name: "Xinyu Hua"
    location: "Boston, MA"

collections:
    posts: 
        title: Blog posts
        description: "opinions are my own."

