# Dependencies
#markdown:         redcarpet
highlighter:        pygments 

# Permalinks
permalink:        pretty

# Setup
title:            Xinyu Hua
tagline:          'Research Homepage'
description:      'This website is built on <a href="http://lanyon.getpoole.com" target="_blank">Lanyon</a> theme in <a href="http://jekyllrb.com" target="_blank">Jekyll</a>'
url:              http://xinyuhua.github.io/
baseurl:          
resourceurl:      '/resources'

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
